### ISSUE TITLE
If deploying to cocoapods fails, the job is still successful

### ISSUE THREAD

**Issue by LitterSun** [michaelhenry/deploy-to-cocoapods-github-action#4]
[!] Found podspec `GrowingAnalytics.podspec`
Updating spec repo `trunk`
Validating podspec
 -> GrowingAnalytics
 -> GrowingAnalytics (0.0.1)
    - WARN  | summary: The summary is not meaningful.
    - ERROR | [iOS] unknown: Encountered an unknown error ([!] /usr/local/bin/git clone https://github.com/growingio/growingio-sdk-ios-autotracker.git /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20201217-4863-12ud63c --template= --single-branch --depth 1 --branch 0.0.1

Cloning into '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20201217-4863-12ud63c'...
warning: Could not find remote branch 0.0.1 to clone.
fatal: Remote branch 0.0.1 not found in upstream origin
) during validation.

[!] The spec did not pass validation, due to 1 error.

![image](https://user-images.githubusercontent.com/15814506/102470312-c8016380-408e-11eb-9d5e-3b616d830077.png)

**Comment by th-anguyen** [comment]
+1.  I am seeing this happen in my repository as well.  The publish failed but job still showed successful.

**Comment by michaelhenry** [comment]
oh i think i know why, there is a typo error in here https://github.com/michaelhenry/deploy-to-cocoapods-github-action/blob/a7f9899697098d49448d264e1d8eedbdd69a6983/main.js#L2

this should be `-eo` 

will fix this soon. thank you.

**Comment by th-anguyen** [comment]
Thanks @michaelhenry! You da man.

**Comment by michaelhenry** [comment]
@th-anguyen you're welcome. thanks to you too. 🍻

**Comment by bejado** [comment]
I'm still seeing this behavior with 745686ab065f90596e0d5cfcf97bb2416d94262e: https://github.com/google/filament/actions/runs/7672082848

The job succeeds, even though authentication with CocoaPods trunk failed:

```
[!] Authentication token is invalid or unverified. Either verify it with the email that was sent or register a new session.
```
